services:
  web:
    build:
      context: .
    container_name: web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - redis
      - celery_worker
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    restart: always
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - app-network

    
networks:
  app-network:
      driver: bridge