# Generated by Django 5.0.6 on 2024-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='car',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='colored',
        ),
        migrations.RemoveField(
            model_name='car',
            name='walk',
        ),
        migrations.AddField(
            model_name='car',
            name='abs_locking',
            field=models.BooleanField(default=False, verbose_name='ABS'),
        ),
        migrations.AddField(
            model_name='car',
            name='air_conditioner',
            field=models.BooleanField(default=False, verbose_name='Kondisioner'),
        ),
        migrations.AddField(
            model_name='car',
            name='central_locking',
            field=models.BooleanField(default=False, verbose_name='Mərkəzi qapanma'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('baki', 'Bakı'), ('ganja', 'Gəncə'), ('sumqayit', 'Sumqayıt'), ('mingachevir', 'Mingəçevir'), ('shirvan', 'Şirvan'), ('naftalan', 'Naftalan'), ('shaki', 'Şəki'), ('yevlakh', 'Yevlax'), ('khirdalan', 'Xırdalan'), ('shusha', 'Şuşa'), ('lyankaran', 'Lənkəran'), ('khachmaz', 'Xaçmaz'), ('jalilabad', 'Cəlilabad'), ('goychay', 'Göyçay'), ('goranboy', 'Goranboy'), ('gazakh', 'Qazax'), ('gakh', 'Qax'), ('gobustan', 'Qobustan'), ('agadag', 'Ağdaş'), ('agadara', 'Ağdərə'), ('agadam', 'Ağdam'), ('lerik', 'Lerik')], default='Bakı', max_length=100, verbose_name='Şəhər'),
        ),
        migrations.AddField(
            model_name='car',
            name='contact_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Adınız'),
        ),
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='car',
            name='front_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Ön görünüşü'),
        ),
        migrations.AddField(
            model_name='car',
            name='heated_seats',
            field=models.BooleanField(default=False, verbose_name='Oturacaqların isidilməsi'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Ön paneli'),
        ),
        migrations.AddField(
            model_name='car',
            name='leather_seat',
            field=models.BooleanField(default=False, verbose_name='Dəri salon'),
        ),
        migrations.AddField(
            model_name='car',
            name='light_alloy_whells',
            field=models.BooleanField(default=False, verbose_name='Yüngül lehimli disklər'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=1, verbose_name='Yuruyus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_unit',
            field=models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='painted',
            field=models.BooleanField(default=False, verbose_name='Renglenib'),
        ),
        migrations.AddField(
            model_name='car',
            name='parking_radar',
            field=models.BooleanField(default=False, verbose_name='Park radarı'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon nömrəsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price_currency',
            field=models.CharField(choices=[('₼', 'AZN'), ('$', 'USD'), ('€', 'EUR')], default='AZN', max_length=3),
        ),
        migrations.AddField(
            model_name='car',
            name='rain_sensor',
            field=models.BooleanField(default=False, verbose_name='Yağış sensoru'),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_view_camera',
            field=models.BooleanField(default=False, verbose_name='Arxa görüntü kamerası'),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Arxa görünüşü'),
        ),
        migrations.AddField(
            model_name='car',
            name='side_curtains',
            field=models.BooleanField(default=False, verbose_name='Yan pərdələr'),
        ),
        migrations.AddField(
            model_name='car',
            name='sundroof',
            field=models.BooleanField(default=False, verbose_name='Lyuk'),
        ),
        migrations.AddField(
            model_name='car',
            name='ventilatet_seats',
            field=models.BooleanField(default=False, verbose_name='Oturacaqların ventilyasiyası'),
        ),
        migrations.AddField(
            model_name='car',
            name='xenon_lights',
            field=models.BooleanField(default=False, verbose_name='Ksenon lampalar'),
        ),
        migrations.AlterField(
            model_name='car',
            name='damage_have',
            field=models.BooleanField(default=False, verbose_name='Vurugu var'),
        ),
        migrations.AlterField(
            model_name='car',
            name='for_accident_or_spare_parts',
            field=models.BooleanField(default=False, verbose_name='Qezali ve ya ehtiyyat hisseler ucun'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət'),
        ),
        migrations.DeleteModel(
            name='CarFeatures',
        ),
        migrations.DeleteModel(
            name='CarImages',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
