# Generated by Django 5.0.6 on 2024-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_carimages_car_remove_contactinfo_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='collected_for_which_market',
            field=models.CharField(choices=[('america', 'Amerika'), ('europa', 'Avropa'), ('china', 'Çin'), ('dubai', 'Dubay'), ('korea', 'Koreya'), ('resmi_diller', 'Rəsmi diler'), ('russia', 'Rusiya'), ('japon', 'Yaponiya')], max_length=32, verbose_name='Hansi bazar  ucun yigilib'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('blue', 'Blue'), ('red', 'Red'), ('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('orange', 'Orange')], max_length=32, verbose_name='Reng'),
        ),
        migrations.AlterField(
            model_name='car',
            name='new_bord',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup'), ('van', 'Van')], max_length=32, verbose_name='Ban novu'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_number',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '8+')], verbose_name='Necenci sahibisiniz?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_currency',
            field=models.CharField(choices=[('₼', 'AZN'), ('$', 'USD'), ('€', 'EUR')], default='AZN', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_count',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '8+')], verbose_name='Yerlerin sayi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17, verbose_name='VIN_kod'),
        ),
    ]
