# Generated by Django 5.0.6 on 2024-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('mercedes', 'Mercedes-Benz'), ('bmw', 'BMW'), ('audi', 'Audi'), ('volkswagen', 'Volkswagen'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai')], max_length=32, verbose_name='Makra'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('toyota_corolla', 'Toyota Corolla'), ('toyota_camry', 'Toyota Camry'), ('honda_civic', 'Honda Civic'), ('honda_accord', 'Honda Accord'), ('ford_mustang', 'Ford Mustang'), ('ford_focus', 'Ford Focus'), ('chevrolet_camaro', 'Chevrolet Camaro'), ('chevrolet_malibu', 'Chevrolet Malibu'), ('mercedes_c_class', 'Mercedes-Benz C-Class'), ('mercedes_e_class', 'Mercedes-Benz E-Class'), ('bmw_3_series', 'BMW 3 Series'), ('bmw_5_series', 'BMW 5 Series'), ('audi_a4', 'Audi A4'), ('audi_q5', 'Audi Q5'), ('volkswagen_golf', 'Volkswagen Golf'), ('volkswagen_passat', 'Volkswagen Passat'), ('nissan_altima', 'Nissan Altima'), ('nissan_maxima', 'Nissan Maxima'), ('hyundai_elantra', 'Hyundai Elantra'), ('hyundai_sonata', 'Hyundai Sonata')], max_length=32, verbose_name='Model'),
        ),
    ]
