# Generated by Django 5.0.6 on 2024-07-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mileage_alter_car_mileage_unit_alter_car_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Yuruyus'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_unit',
            field=models.ForeignKey(default='km', on_delete=django.db.models.deletion.CASCADE, to='user.mileage'),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
