# Generated by Django 5.0.6 on 2024-07-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_fueltypechoices_alter_car_price_alter_car_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.transmissionchoices', verbose_name='Surretler qutusu'),
        ),
    ]
