# Generated by Django 5.0.6 on 2024-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_transmissionchoices_alter_car_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTypeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
