# Generated by Django 5.0.6 on 2024-07-02 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_colorchoices_remove_car_new_bord_car_new_bord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.colorchoices', verbose_name='Reng'),
        ),
        migrations.RemoveField(
            model_name='car',
            name='new_bord',
        ),
        migrations.AddField(
            model_name='car',
            name='new_bord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.bodytypechoices', verbose_name='Ban novu'),
            preserve_default=False,
        ),
    ]
