# Generated by Django 5.0.6 on 2024-07-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_marketchoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='collected_for_which_market',
            field=models.ForeignKey(default='Bakı', on_delete=django.db.models.deletion.CASCADE, to='user.marketchoices', verbose_name='Hansi bazar  ucun yigilib'),
        ),
    ]
