# Generated by Django 5.0.6 on 2024-07-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_citychoices_alter_car_collected_for_which_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.ForeignKey(default='Bakı', on_delete=django.db.models.deletion.CASCADE, to='user.citychoices', verbose_name='Şəhər'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.carbrands', verbose_name='Makra'),
        ),
    ]
