# Generated by Django 5.0.6 on 2024-07-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_carbrands_alter_car_city_alter_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChoies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.modelchoies', verbose_name='Model'),
        ),
    ]
