# Generated by Django 5.0.6 on 2024-07-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_modelchoies_alter_car_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCountChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='YearChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.carbrands', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ownercount', verbose_name='Necenci sahibisiniz?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seatcountchoices', verbose_name='Yerlerin sayi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.yearchoices', verbose_name='il'),
        ),
    ]
