# Generated by Django 5.0.6 on 2024-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_ownercount_seatcountchoices_yearchoices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercount',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
