# Generated by Django 5.0.6 on 2024-07-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_ownercount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RenameModel(
            old_name='CarBrands',
            new_name='Brand',
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelChoies',
        ),
    ]
