# Generated by Django 5.0.6 on 2024-07-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_car_car_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.carmodel', verbose_name='Model'),
        ),
    ]
