# Generated by Django 5.0.6 on 2024-07-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_car_brand_alter_car_car_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_models',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user.carmodel', verbose_name='Model'),
        ),
    ]
