# Generated by Django 5.0.6 on 2024-07-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_car_car_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.transmissiontype', verbose_name='Ötürücü'),
        ),
    ]
