# Generated by Django 5.0.6 on 2024-07-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_transmissiontype_car_transmission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='front_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/img_cars', verbose_name='Ön görünüşü'),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/img_cars', verbose_name='Ön paneli'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rear_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/img_cars', verbose_name='Arxa görünüşü'),
        ),
    ]
